### ISSUE TITLE
Expand personas

### ISSUE THREAD

**Issue by steffencruz** [macrocosm-os/prompting#119]
## Moods
- terse
- playful
- hyped
- foul
- celebratory
- indignant

## Tones
- skeptical
- apologetic
- unapologetic
- nonchalant
- eager
- confused

**Comment by mccrindlebrian** [comment]
@steffencruz Did you do this in your recent commits?

**Comment by steffencruz** [comment]
Yes I’m running some experiments on this in a development branch called benchmark/tasks

**Comment by Hollyqui** [comment]
Personas have been expanded
