### ISSUE TITLE
Ensure that math challenges contain necessary information

### ISSUE THREAD

**Issue by steffencruz** [macrocosm-os/prompting#122]
There are edge cases where math challenges modify or otherwise corrupt the underlying math problem. We can address this by validating the challenge. Once flagged, the options are to regenerate the challenge or to reject the task altogether.

Two ways to detect inconsistent math challenges:

1. check that all numeric values in the query are also present
2. each math task context specifies all essential keywords (including numbers) that must be present

**Comment by steffencruz** [comment]
@bkb2135 is this now implemented?

**Comment by bkb2135** [comment]
Not currently, I thought that this would be solved when we implement the pre-generated paraphrase protocol, but I haven't gotten around to that yet. It's definitely on my list though.
