### ISSUE TITLE
keep receiving this resync_metagraph() 

### ISSUE THREAD

**Issue by MohamedHamdy28** [macrocosm-os/prompting#260]
when I run the miner, I keep receiving this resync_metagraph() and when I try to request the miner from the client.py with a simple request, I get an empty completion. 

I didn't change anything in the code yet.
![image](https://github.com/macrocosm-os/prompting/assets/71794972/7fca5f54-ddeb-4cf6-b9b4-f0e87315d0c6)
![image](https://github.com/macrocosm-os/prompting/assets/71794972/05ba9b66-4311-4ce4-899a-f7277474b575)

script for running the miner:
pm2 start neurons/miners/test/echo.py --interpreter python3 --name openai_miner -- --netuid 61  --subtensor.network test --wallet.name test-coldkey --wallet.hotkey my_first_hotkey --axon.port 21988 --logging.debug --wandb.on true

**Comment by MohamedHamdy28** [comment]
I noticed that resync_metagraph() is called every time (self.block - self.metagraph.last_update[self.uid]) > self.config.neuron.epoch_length, however,  self.metagraph.last_update[self.uid] is not updated after calling resync_metagraph() so it keeps calling resync_metagraph(). 

I don't know if this is the correct solution to this problem but after updating the self.metagraph.last_update[self.uid] with the current block, it didn't call resync_metagraph() anymore.

Hope someone corrects me

**Comment by bkb2135** [comment]
Addressed in [This Issue](https://github.com/macrocosm-os/prompting/pull/271)
