### ISSUE TITLE
Add typing hints for all the arguments and return types

### ISSUE THREAD

**Issue by dbobrenko** [macrocosm-os/prompting#291]
# Request

Add `typing` hints for all the arguments and return types across the entire project.

## Suggested Steps

1. Review all functions and methods.
2. Add type hints for all arguments and return types (return type None is not need to be explicitly defined).
3. Update documentation if necessary to reflect the changes.

## Benefits

- Improved code readability.
- Better development experience with IDEs providing type-checking and autocompletion.
- Reduced runtime errors through earlier detection of type mismatches.

**Comment by frozenmafia** [comment]
Hi @dbobrenko,

I've just created my first [PR](https://github.com/macrocosm-os/prompting/pull/296) to the project. As this is my initial open-source contribution, I would greatly appreciate any feedback you may have on the process. If everything looks good, I'm eager to continue contributing further.

Thank you in advance!
