### ISSUE TITLE
Change single quotes for strings to double quotes

### ISSUE THREAD

**Issue by dbobrenko** [macrocosm-os/prompting#299]
## Problem statement

The project currently uses a mix of single `'` and double quotes `"`, which makes the style inconsistent, and will fail linter checks. 

## Proposal

Standardize all strings to use double quotes " for consistency.

Exceptions: strings within strings, e.g., `bt.logging.info(f"Some 'string' here")` must be defined with single quotes.

Standardizing quotes will improve code readability and simplify searching within the project.

This can be done automatically with code formatters, like: `ruff`, `black`, etc.

**Comment by Huzaifa666** [comment]
Is this still open ?
I checked out the packages and it does have double quotes
Single quotes are mostly there in yaml files

**Comment by dbobrenko** [comment]
> Is this still open ? I checked out the packages and it does have double quotes Single quotes are mostly there in yaml files

Yes, there are still some parts of code where `'` is being used:

https://github.com/macrocosm-os/prompting/blob/main/prompting/cleaners/all_cleaners.py#L101
https://github.com/macrocosm-os/prompting/blob/main/prompting/cleaners/all_cleaners.py#L126
https://github.com/macrocosm-os/prompting/blob/main/prompting/tasks/date_qa.py#L43
etc

**Comment by dbobrenko** [comment]
No longer relevant.
